id: P5A90DC48
initial_creation_type: ocr
source_metadata:
  volumes:
    76b4ea4edd804c24b1295d909114b2b3:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: འཕགས་པ་རྟ་མགྲིན་གྱི་སྒྲུབ་ཐབས།
      total_pages: 1044
      volume_number: 38
